### ISSUE TITLE
List stuff in reverse chronological order (newest to oldest)

### ISSUE THREAD

**Issue by murphyk** [janosh/awesome-normalizing-flows#28]
Hi! This page is awesome (hence the name :) However it would be even more useful if you listed things  (especially code) newest first, instead of oldest first, ie reverse chronological order.

**Comment by jejjohnson** [comment]
I personally think this is potentially a good idea. What do you think @janosh ?

**Comment by janosh** [comment]
Yes, sounds sensible. Though rather than doing the reshuffling manually, I'd like to be a bit more thorough about it and generate the readme programmatically from source data in a `data.yml` file. Something like

```yml
publications:
  - id: 1
    title: 'Iterative Gaussianization: from ICA to Random Rotations'
    url: https://arxiv.org/abs/1602.00229
    date: Apr 1, 2011
    authors: Laparra et. al.
    description: Normalizing flows in the form of Gaussianization in an iterative format. Also shows connections to information theory.

  - id: 2
    title: Non-linear Independent Components Estimation
    url: https://arxiv.org/abs/1410.8516
    date: Oct 30, 2014
    authors: Laurent Dinh, David Krueger, Yoshua Bengio.
    description: Introduces the additive coupling layer (NICE) and shows how to use it for image generation and inpainting.

# ...
```

 That would make it easier to

- add new items to this list in the future without having to worry about markdown formatting
- reshuffle the data again (if the need ever arises)
- ensure all items conform to the schema, i.e. have all required keys: id, title, url, date, authors, description
- use the data downstream in case people want to use it for plots/data vis
